pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
              sh 'echo manoj is good'
        script{
          sh "mvn clean install"
          sh 'java -cp target/hello-world-1.0-SNAPSHOT.jar com.helloworld'

      }}
      
    }
            
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
  }
}
